[package]
name = "another-rxrust"
description = "another implementation of `rxRust`."
edition = "2021"
license = "MIT"
homepage = "https://github.com/CODIANZ/another-rxrust"
repository = "https://github.com/CODIANZ/another-rxrust"
keywords = ["reactivex", "rx", "rxrust"]
version = "0.0.7"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
